version: '3'
services:
  api:
    build:
      context: .
    working_dir: /app
    volumes:
      - './app:/app'
    ports:
      - 8001:8000
    environment:
      PYTHONPATH: "${PYTHONPATH}:/app/"
 
